# Best hyperparameters for each RFSD dataset.
amazon:
  data_dir: data/amazon
  learning_rate: 2e-4
  num_negatives: 10
  weight_decay: 5e-4
  regularization_weight: 1e-4
  num_clusters: 2
  user_top_k: 80
  item_top_k: 10
  user_graph_layers: 3
  item_graph_layers: 1
  cluster_temperature: 1.0
  contrastive_temperature: 0.1
  contrastive_weight: 0.1

yelp:
  data_dir: data/yelp
  learning_rate: 1e-4
  num_negatives: 20
  weight_decay: 5e-5
  regularization_weight: 5e-3
  num_clusters: 2
  user_top_k: 40
  item_top_k: 60
  user_graph_layers: 2
  item_graph_layers: 1
  cluster_temperature: 10.0
  contrastive_temperature: 1e-1
  contrastive_weight: 1e-3

steam:
  data_dir: data/steam
  learning_rate: 0.002
  num_negatives: 5
  weight_decay: 0.0005
  regularization_weight: 0.001
  num_clusters: 4
  user_top_k: 40
  item_top_k: 20
  user_graph_layers: 2
  item_graph_layers: 1
  cluster_temperature: 10.0
  contrastive_temperature: 0.01
  contrastive_weight: 0.01
